version: '3.7'

services:
  base:
    image: vuln_django
    container_name: vuln-django
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - SERVER_PORT=${SERVER_PORT:-8020}
    environment:
      - SERVER_PORT=${SERVER_PORT:-8020}
    ports:
      - ${SERVER_PORT:-8020}:${SERVER_PORT:-8020}
    entrypoint:
      - /opt/app/start-server.sh
